const { Octokit } = require('octokit');
const simpleGit = require('simple-git');
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

class GitHubService {
    constructor(accessToken) {
        this.octokit = new Octokit({ auth: accessToken });
        this.git = simpleGit();
        this.tempDir = path.join(__dirname, '../../temp_repos');

        if (!fs.existsSync(this.tempDir)) {
            fs.mkdirSync(this.tempDir, { recursive: true });
        }
    }

    async createPullRequest({ owner, repo, errorId, originalFile, fixedCode, filePath, description }) {
        const branchName = `debugmate/fix-${errorId}-${uuidv4().slice(0, 8)}`;
        const repoUrl = `https://github.com/${owner}/${repo}.git`; // In prod, use token in URL for auth
        const localRepoPath = path.join(this.tempDir, `${repo}-${uuidv4()}`);

        try {
            console.log(`Cloning ${repo}...`);
            // 1. Clone Repository
            await this.git.clone(repoUrl, localRepoPath);

            const gitLocal = simpleGit(localRepoPath);

            // 2. Create Branch
            console.log(`Creating branch ${branchName}...`);
            await gitLocal.checkoutLocalBranch(branchName);

            // 3. Apply Fix
            const fullFilePath = path.join(localRepoPath, filePath);
            console.log(`Writing fix to ${fullFilePath}...`);
            fs.writeFileSync(fullFilePath, fixedCode);

            // 4. Commit Changes
            await gitLocal.add('.');
            await gitLocal.commit(`fix: resolve error ${errorId} in ${path.basename(filePath)}`);

            // 5. Push Branch
            // Note: In a real app, you need to configure remote with auth token
            // await gitLocal.push('origin', branchName); 
            // For this demo code, we'll assume the environment is set up or use Octokit to create blob/tree/commit directly (safer for serverless)

            // ALTERNATIVE: Using GitHub API directly (No cloning required - Faster & Safer)
            // This is the preferred method for "Auto-Fix" bots
            const pr = await this.createPRViaAPI(owner, repo, branchName, filePath, fixedCode, description);

            // Cleanup
            fs.rmSync(localRepoPath, { recursive: true, force: true });

            return pr;

        } catch (error) {
            console.error('Error in createPullRequest:', error);
            if (fs.existsSync(localRepoPath)) {
                fs.rmSync(localRepoPath, { recursive: true, force: true });
            }
            throw error;
        }
    }

    // Pure API approach (No cloning)
    async createPRViaAPI(owner, repo, branchName, filePath, content, description) {
        // 1. Get reference to main branch
        const { data: refData } = await this.octokit.rest.git.getRef({
            owner,
            repo,
            ref: 'heads/main', // Assuming main is default
        });
        const mainSha = refData.object.sha;

        // 2. Create new branch
        await this.octokit.rest.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${branchName}`,
            sha: mainSha,
        });

        // 3. Get current file SHA (if it exists)
        let fileSha;
        try {
            const { data: fileData } = await this.octokit.rest.repos.getContent({
                owner,
                repo,
                path: filePath,
                ref: branchName,
            });
            fileSha = fileData.sha;
        } catch (e) {
            // File might be new
        }

        // 4. Update file content
        await this.octokit.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path: filePath,
            message: `fix: auto-fix for ${path.basename(filePath)}`,
            content: Buffer.from(content).toString('base64'),
            branch: branchName,
            sha: fileSha,
        });

        // 5. Create Pull Request
        const { data: pr } = await this.octokit.rest.pulls.create({
            owner,
            repo,
            title: `fix: Automated resolution for ${path.basename(filePath)}`,
            head: branchName,
            base: 'main',
            body: `## DebugMate Auto-Fix 🤖\n\n${description}\n\nThis PR was automatically generated by DebugMate.`,
        });

        return pr;
    }
}

module.exports = GitHubService;
