import { useState } from 'react';
import { Copy, Check, Download, Share2 } from 'lucide-react';
import { cn } from '../../lib/utils';

export type CopyFormat = 'markdown' | 'plain' | 'json';

interface CopyErrorButtonProps {
    errorMessage: string;
    errorType: string;
    rootCause: string;
    severity: string;
    stackTrace?: string;
    codeSnippet?: string;
    filePath?: string;
    lineNumber?: number;
    language?: string;
    solutions?: Array<{ title: string; description: string }>;
    className?: string;
}

export const CopyErrorButton = ({
    errorMessage,
    errorType,
    rootCause,
    severity,
    stackTrace,
    codeSnippet,
    filePath,
    lineNumber,
    language = 'TypeScript',
    solutions,
    className,
}: CopyErrorButtonProps) => {
    const [copied, setCopied] = useState(false);
    const [format, setFormat] = useState<CopyFormat>('markdown');
    const [showFormats, setShowFormats] = useState(false);

    const generateMarkdown = () => {
        let markdown = `# 🐛 Error Report\n\n`;
        markdown += `## Error Type\n${errorType}\n\n`;
        markdown += `## Severity\n${severity.toUpperCase()} 🔴\n\n`;
        markdown += `## Root Cause\n${rootCause}\n\n`;
        markdown += `## Error Message\n\`\`\`\n${errorMessage}\n\`\`\`\n\n`;

        if (filePath) {
            markdown += `## Location\n- **File**: \`${filePath}\`\n`;
            if (lineNumber) markdown += `- **Line**: ${lineNumber}\n`;
            markdown += `- **Language**: ${language}\n\n`;
        }

        if (stackTrace) {
            markdown += `## Stack Trace\n\`\`\`\n${stackTrace}\n\`\`\`\n\n`;
        }

        if (codeSnippet) {
            markdown += `## Code Context\n\`\`\`${language.toLowerCase()}\n${codeSnippet}\n\`\`\`\n\n`;
        }

        if (solutions && solutions.length > 0) {
            markdown += `## Suggested Solutions\n\n`;
            solutions.forEach((solution, index) => {
                markdown += `### ${index + 1}. ${solution.title}\n${solution.description}\n\n`;
            });
        }

        markdown += `---\n*Generated by DebugMate AI*`;
        return markdown;
    };

    const generatePlainText = () => {
        let text = `ERROR REPORT\n${'='.repeat(50)}\n\n`;
        text += `Error Type: ${errorType}\n`;
        text += `Severity: ${severity.toUpperCase()}\n`;
        text += `Root Cause: ${rootCause}\n\n`;
        text += `Error Message:\n${errorMessage}\n\n`;

        if (filePath) {
            text += `Location:\n`;
            text += `  File: ${filePath}\n`;
            if (lineNumber) text += `  Line: ${lineNumber}\n`;
            text += `  Language: ${language}\n\n`;
        }

        if (stackTrace) {
            text += `Stack Trace:\n${stackTrace}\n\n`;
        }

        if (codeSnippet) {
            text += `Code Context:\n${codeSnippet}\n\n`;
        }

        if (solutions && solutions.length > 0) {
            text += `Suggested Solutions:\n`;
            solutions.forEach((solution, index) => {
                text += `\n${index + 1}. ${solution.title}\n   ${solution.description}\n`;
            });
        }

        text += `\n${'='.repeat(50)}\nGenerated by DebugMate AI`;
        return text;
    };

    const generateJSON = () => {
        const data = {
            errorType,
            severity,
            rootCause,
            errorMessage,
            location: filePath ? {
                file: filePath,
                line: lineNumber,
                language,
            } : undefined,
            stackTrace,
            codeSnippet,
            solutions: solutions?.map(s => ({
                title: s.title,
                description: s.description,
            })),
            timestamp: new Date().toISOString(),
            generatedBy: 'DebugMate AI',
        };
        return JSON.stringify(data, null, 2);
    };

    const getFormattedContent = () => {
        switch (format) {
            case 'markdown':
                return generateMarkdown();
            case 'plain':
                return generatePlainText();
            case 'json':
                return generateJSON();
            default:
                return generateMarkdown();
        }
    };

    const handleCopy = async () => {
        try {
            const content = getFormattedContent();
            await navigator.clipboard.writeText(content);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const handleDownload = () => {
        const content = getFormattedContent();
        const extension = format === 'json' ? 'json' : format === 'markdown' ? 'md' : 'txt';
        const filename = `error-report-${Date.now()}.${extension}`;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    const formats: Array<{ value: CopyFormat; label: string; icon: string }> = [
        { value: 'markdown', label: 'Markdown', icon: '📝' },
        { value: 'plain', label: 'Plain Text', icon: '📄' },
        { value: 'json', label: 'JSON', icon: '🔧' },
    ];

    return (
        <div className={cn("relative inline-flex gap-2", className)}>
            {/* Main Copy Button */}
            <button
                onClick={handleCopy}
                className={cn(
                    "flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-all text-base",
                    copied
                        ? "bg-green-500/20 text-green-400 border border-green-500/30"
                        : "bg-white/5 hover:bg-white/10 text-white border border-white/10 hover:border-white/20"
                )}
            >
                {copied ? (
                    <>
                        <Check className="w-4 h-4" />
                        <span>Copied!</span>
                    </>
                ) : (
                    <>
                        <Copy className="w-4 h-4" />
                        <span>Copy Error</span>
                    </>
                )}
            </button>

            {/* Format Selector */}
            <div className="relative">
                <button
                    onClick={() => setShowFormats(!showFormats)}
                    className="px-3 py-2.5 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 transition-all"
                    title="Choose format"
                >
                    <Share2 className="w-4 h-4 text-white" />
                </button>

                {showFormats && (
                    <div className="absolute right-0 top-full mt-2 w-48 bg-[#1a1a1a] border border-white/10 rounded-lg shadow-2xl z-50 overflow-hidden animate-in slide-in-from-top-2">
                        <div className="p-2 border-b border-white/10">
                            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider px-2 py-1">
                                Format
                            </p>
                        </div>
                        {formats.map((fmt) => (
                            <button
                                key={fmt.value}
                                onClick={() => {
                                    setFormat(fmt.value);
                                    setShowFormats(false);
                                }}
                                className={cn(
                                    "w-full text-left px-4 py-2.5 text-base transition-colors flex items-center gap-2",
                                    format === fmt.value
                                        ? "bg-blue-500/20 text-blue-400"
                                        : "text-gray-300 hover:bg-white/5 hover:text-white"
                                )}
                            >
                                <span>{fmt.icon}</span>
                                <span>{fmt.label}</span>
                                {format === fmt.value && (
                                    <Check className="w-4 h-4 ml-auto" />
                                )}
                            </button>
                        ))}
                        <div className="p-2 border-t border-white/10">
                            <button
                                onClick={() => {
                                    handleDownload();
                                    setShowFormats(false);
                                }}
                                className="w-full text-left px-4 py-2.5 text-base text-gray-300 hover:bg-white/5 hover:text-white transition-colors flex items-center gap-2 rounded-md"
                            >
                                <Download className="w-4 h-4" />
                                <span>Download File</span>
                            </button>
                        </div>
                    </div>
                )}
            </div>

            {/* Click outside to close */}
            {showFormats && (
                <div
                    className="fixed inset-0 z-40"
                    onClick={() => setShowFormats(false)}
                />
            )}
        </div>
    );
};
